### ISSUE TITLE
Classlojure should ship a copy of the EPL license in LICENSE

### ISSUE THREAD

**Issue by wwentland** [ninjudd/classlojure#5]
One requirement for licensing code under the EPL is that "a copy of this Agreement [the EPL] must be included with each copy of the Program." [0]. Unfortunately classlojure does not comply with this requirement even though its project.clj claims that it is licensed under the EPL.

Additionally it would be nice if _every_ source file could mention its license explicitly. That is it should include a statement of copyright and, for the EPL, a header such as:

```
THE ACCOMPANYING PROGRAM IS PROVIDED UNDER THE TERMS OF THIS ECLIPSE PUBLIC
LICENSE ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THE PROGRAM
CONSTITUTES RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT.
```

Please fix this issue and release a new version of classlojure as it is not legally distributable in its current form.

[0] http://www.eclipse.org/legal/epl-v10.html → 3. REQUIREMENTS

**Comment by Raynes** [comment]
Agreed that there should be a LICENSE file. It must have been overlooked. I do not agree that we should put license headers in every file. I've never been a fan of that, and I'm pretty sure it isn't legally necessary. Correct me if I'm wrong, of course. IANAL. :)
